id = "pace-pro-theme"
name = "Pace Pro"
version = "0.1.0"
schema_version = 1
authors = ["VitMach Converted from VS Code Pace Dark by Fabian Hilleh"]
description = "Pace Dark, Pace Dark Pro OLED and Pace Light Pro themes"
repository = "https://github.com/VMachihin/pace-theme-pro"
